### ISSUE TITLE
Streamline Self-Managed installation guides

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#1787]
Streamline Self-Managed installation guides, to reduce circular linking/navigation and number of page views needed to understand the installation

**Comment by akeller** [comment]
FYI @aabouzaid, since you designed the structure for this area of the docs.

I could see this being quite a large project. Would be good for @christinaausley and @aabouzaid to align on next steps and content architecture before moving forward.

**Comment by christinaausley** [comment]
@aabouzaid Feel free to pop some time on my calendar if you would like to discuss further.

**Comment by aabouzaid** [comment]
@christian-konrad could you please add more details about the problem and why it's a problem in the first place?

The problem is a bit unclear to me, especially since we have a dedicated section called [guides](https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/guides/) and not sure if that's related or it's only about the [deployment](https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/deploy/) part.

**Comment by akeller** [comment]
@christian-konrad bumping this. Any more info you can add here?
