### ISSUE TITLE
Create proposal to revamp/redesign the docs home page

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2070]
# Overview

Our homepage serves 3 broad purposes, as defined by three content sections:

* Get Started/Sign Up
* Defining our docs top nav structure
* Linking to our three getting started use cases

This is great for beginners and folks new to Camunda, but may not be the best fit for our maturing platform and user base. 

We should come up with a set of proposals and solicit feedback on how to best use this page for all users, beginners to advanced, pro-code and low-code. 

# To do

- [x] Collect feedback (completed by April 26)
- [x] Research other docs landing pages (completed by April 26)
- [x] Draft up proposals (completed by April 26)
- [x] Submit proposals for feedback (completed by April 26)
- [x] Address feedback, determine draft changes (completed by May 3)
- [ ] Draft changes in PR (completed by May 27)

**Comment by akeller** [comment]
I _reaaaally_ like this as a project for you! 

I'd love to see a proposal on what content we should have on our homepage based on how things have changed since we launched! Do we add more explanation for what Camunda is? Do we add a brief intro for Self Managed? Can we figure out a way to highlight new things in docs? 

You can also research other docs sites to see what they do on their main pages to draw inspiration. Part research, part proposal!

**Comment by christinaausley** [comment]
[Survey in progress](https://camunda.slack.com/archives/C026U8GBNSW/p1713880992054139), circulated among the onboarding team and DevRel team as well. Digging through related sites and drafting up notes currently.

Updated description with timeline of tasks 👍

**Comment by christinaausley** [comment]
Proposal and feedback are collected at https://docs.google.com/document/d/1IWpDWiaavNVMgKcUUbD3h3ru6mWOAwLgCpXyudlU6A4/edit?usp=sharing 👍

**Comment by akeller** [comment]
@christinaausley This looks amazing! Let me gush a little more:

* I love that you used an internal survey mechanism to collect feedback
* I love that you included that in your proposal doc and tried to accommodate all of it
* I love that you included a mix of things are are easily achievable and static as well as some areas that need a little more thought and development (proposals don't need to be 100% and we should expect to adjust them)

1 challenge for you - if you need to deliver this incrementally, what would you address first? How would you iterate?

**Comment by christinaausley** [comment]
I have a pretty good draft going in https://github.com/camunda/camunda-docs/pull/3792, and honestly we could likely merge this in if approved. I'd just need to revert the footer, as that is still a WIP.

FYI that I've submitted a marketing ticket for custom top and bottom banners 👍 

Still to do IMO:
- [ ] Are features the only way we can outline the cards here? Can I add a div around each one to apply a background, and round the corners?
- [ ] Essentially, how can I make these little icon cards look cool? Should the icons themselves be orange? Alternating orange and black?- [ ] Should we apply a video to the footer, rather than an image or a code snippet? What if there isn't any video content available? If there is, is it maintainable?
- [ ] I don't love the way the footer looks at all right now (so for anyone following this please ignore!!) -- need to figure out how camunda.com applies a cool "feature" box, and how I could apply this, too.
- [ ] Does the design team want to create a custom background for the header and/or footer?
- [ ] As a user scrolls down the page, can I have the icons gradually fade/slide/transition in? How do I make them hover on mouse hover like the original version?

Planning to tackle three of these boxes each week, with plans for this to be ready for final review in two weeks.

**Comment by christinaausley** [comment]
To meet with @karl-heinsen next week to polish up some of the design and CSS, as well as collect Karl's overall feedback 👍

**Comment by melanie-butcher** [comment]
@christinaausley - I will add Philippa as a designer to work with you on this project. Welcome to the team, @PhilippaC22 !

**Comment by christinaausley** [comment]
Thank you @melanie-butcher and welcome @PhilippaC22! Excited to work together.

Planning to get the first iteration cleaned up this week so I have a clean slate to work with @PhilippaC22. I just need to get the cards to align, and clean up a few nit picky things.

@PhilippaC22 and I can work together on the next iteration, which I can start looking at next week 👍 Could be interesting to loop in a UX researcher as well. Karl pointed me to @lmbateman, but will touch base with @PhilippaC22 first!

Still waiting to hear back from marketing on a custom banner for the header and footer, but the request is out there regardless.

**Comment by christinaausley** [comment]
I have things in a place where I think we can merge a first iteration and start with a clean slate. I feel like the current PR goes beyond the scope of this issue anyways, as we made changes beyond just launching a proposal and soliciting feedback.

I realize we may want to re-evaluate the landing page based on SaaS/SM feedback, so I propose an issue for a second iteration, where I can also work with @PhilippaC22 (new designer), and will also have custom templates for the top and bottom banners from marketing CC Grant Eaton.

Thoughts? If we feel the first iteration is a sufficient improvement to close this out, I'll get another issue launched for a second iteration, or SM/SaaS-specific revamp.

**Comment by christinaausley** [comment]
Second iteration to come with https://github.com/camunda/developer-experience/issues/340.

**Comment by PhilippaC22** [comment]
25th July - Reviewed latest page updates with @mesellings [here] (https://www.figma.com/board/v5ZfeWJFP25MQLrXDXWyPR/Documentation-page-review?node-id=69-191)
Brand decisions are still to be defined by us. So far the consensus is a hybrid between product components and UI for familiarity and marketing assets for visual interest. 
@christinaausley perhaps lets reach out to the brand design team too and see what recommendations they may have after doing the same with marketplace.
