### ISSUE TITLE
Add "create issue" on every page

### ISSUE THREAD

**Issue by falko** [camunda/camunda-docs#2798]
To ease reporting documentation issues, add a link to create issue to bottom of each documentation page similar to the "edit on GitHub" link. Great would be if the current page could automatically be captured in the issue so that reporting issues like #2797 or #2739 becomes easier.

**Comment by akeller** [comment]
@pepopowitz I see this as something in your scope, but I view it as an enhancement, a nice to have. If there is a quick win, I would be ok with exploring it, but I don't know whether Docusaurus supports this OOTB.

**Comment by pepopowitz** [comment]
I am relatively strongly against this feature, and I am inclined to close this as "won't fix". 

1. While it would make it easier to open issues like the ones linked in the description, it would also make it easier to open fly-by "correct this spelling" type of issues. I anticipate that we'd receive a lot more of that second type -- and I would rather nudge people to open PRs for those, as opposed to opening an issue that would likely sit untouched for a long time. While there is indeed a bit of friction for creating the useful issues described in this issue, I think that friction is also contributing to the net improvement of our docs.
2. There is no [built in functionality](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs) for adding this button to every page, so we'd have to invest some effort into building this. For something that I also don't think is a net win, I would prioritize this work low enough that I don't see myself getting to it for a very long time.

I'm open to discussion, but that's my relatively-strong opinion. I'll leave the issue open to gather feedback for a couple days, and then close it unless I'm convinced otherwise.

**Comment by akeller** [comment]
We've recently added 👍 👎 buttons to each page, but won't move forward with this.
