### ISSUE TITLE
Console > Manage clusters > Setting pages only includes info about RBA

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2877]
There are at least two other settings on the [settings page](https://docs.camunda.io/docs/components/console/manage-clusters/settings/) that should be included in the docs:

* Toggling automatic cluster updates
* Deleting the cluster

The screenshot should be updated as well to show all settings, or removed entirely.

<img width="716" alt="image" src="https://github.com/camunda/camunda-docs/assets/1051363/2d2fbb67-0f40-45fe-87b0-f05196acb655">

**Comment by akeller** [comment]
@mesellings this should be a relatively easy one for you to triage as you onboard and start to dig into the product experience. Given that this issue has been open for a while, please determine whether it's still relevant (maybe the product UI and docs have since been updated!). If it's no longer relevant, close the issue with a comment. If it is still relevant, how would you scope this to be improved in a 2-week increment (or less)?

**Comment by mesellings** [comment]
@akeller Taking an initial look at this, the screenshot looks like it was updated, however there doesn't seem to be much actual documentation on the page itself, so I think it is worth some work just to improve the page for customers. Currently it feels like a placeholder page?

My recommendations are:
* Perhaps remove the screenshot entirely - screenshots are useful, but this one might be overkill? The page text should mean we don't need a screenshot.
* Document the settings on the page, at least at a basic level, either as concept or task (e.g. headings for each setting).
* I would change some of the passive voice in the intro paragraph, and bullet them otherwise there is too much 'reading'/not easily scannable. Ideally a single sentence (shortdesc) to introduce the settings tab, followed by important bullets, and headed sections for each setting.

In terms of scope:
* Estimated 1-3 days for investigation into the settings and then to create the content (assuming I have access to everything I need by then).

Is this something you would like me to do?

**Comment by mesellings** [comment]
I will update this page in line with the software as follows:

* Next & 8.5: RBA, Automatic cluster updates, Enforce user task restrictions, Delete cluster
* 8.4 & 8.3: RBA, Delete cluster

**Comment by mesellings** [comment]
@akeller as part of this, I would also look at a few of the connected pages (e.g. Update your cluster) to improve them/align them with these changes - should I create a new issue for this or just include the work in this issue?

**Comment by mesellings** [comment]
@akeller I've created a PR for this work - I think I have completed all the fields etc as per our guidelines.
