### ISSUE TITLE
Product images appear stretched across docs.camunda.io

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#3069]
Reported by @Zelldon via https://camunda.slack.com/archives/C026U8GBNSW/p1702655416996449

**Comment by pepopowitz** [comment]
It appears to affect images that are wider than the main content area, only. The image [on this page](https://stage.docs.camunda.io/docs/components/) is fine, for example.

It looks like Docusaurus sets the height/width explicitly on the image element in HTML, according to the size of the image....and then the CSS overrides `width:100%`...but it doesn't touch the height, which causes it to vertically stretch according to the original image's height.

[Here's an old issue](https://github.com/facebookincubator/infima/issues/229) that talks about something happening in infima, the design system....but I don't know why this would suddenly become an issue for us.

I'm going to roll back locally to see if I can see when the issue was introduced. The fix might be to apply `height:auto` in our custom CSS, but I kind of want to know why it suddenly happened.

**Comment by pepopowitz** [comment]
I rolled back to the previous release locally, and the problem went away.... so there was something in this release. 

<img src="https://media3.giphy.com/media/4EF5LwiRfpBKQUOsoF/giphy.gif"/>

**Comment by pepopowitz** [comment]
Ah, cool. So in the previous release, `height` was being set to `auto` by the classic theme: 

<img width="311" alt="image" src="https://github.com/camunda/camunda-docs/assets/1627089/c57e79f5-0ad8-405c-bb39-4f78a3d7ff06">

In #2944, [I had to specify the OpenAPI plugin's theme](https://github.com/camunda/camunda-docs/blob/66ac50b954bca498bafd382e6bdde4d8ea542f1c/docusaurus.config.js#L376), in order to get all their styles.

I assumed that all the classic theme would still be picked up when I did that, but that appears not to be the case. I'm not sure if it's because the OpenAPI plugin's theme explicitly excludes things, or maybe it uses an old version of infima which is affected by that bug I previously linked to, or maybe 🤷 

Again, adding `height:auto` might fix this specific issue right off the bat...but now I'm worried about what _else_ was un-done by including the OpenAPI plugin's theme. So I'll be digging into that.

<img src="https://media2.giphy.com/media/ZvUc2UBuAGmPol0udh/giphy.gif"/>

**Comment by pepopowitz** [comment]
Oof. [We are not the only ones experiencing the problem](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/626).

Unfortunately, the problem _is_ bigger than just the stretched images. According to that issue, and confirmed from our docs: 

* Admonitions aren't displaying (the text displays, but as plain text on the page instead of styled as a callout).
* Code samples outside of the OpenAPI explorer do not have syntax highlighting.

My instinct is to stop investigating for now, and push up a revert PR, and back this out until we or the plugin authors can figure out a fix. @akeller do you agree with that?

**Comment by akeller** [comment]
Yes - agreed. We have too much critical info and overall docs experience at risk here without immediate action.
