### ISSUE TITLE
Document backup/restore limitations

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda-docs#3376]
Backup of web apps (at least Operate and Tasklist) can not be directly used to "copy" the system to another environment, as it contains only data, but not the templates. We should make it clear in the documentation.

We can also document, what is the proper way to "copy" the system, something like:
1. Configure and run the setup with same app versions (probably also same partition count for Zeebe)
2. Stop the system and follow the restore procedure.

**Comment by michaldytko** [comment]
Related to https://jira.camunda.com/browse/SUPPORT-20726

**Comment by ManuelDittmar** [comment]
Hi @sdorokhova a prospect is asking for the same.

I "easiest" solution would be to adjust the [restore section](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/backup-and-restore/#restore)?

Instead of 

1. Restore the state of [Operate](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/operate-tasklist-backup/), [Tasklist](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/operate-tasklist-backup/), and [Optimize](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/optimize-backup/).
2. Restore zeebe-records* indices from Elasticsearch snapshot.
3. Restore [Zeebe](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore/).
4. Start Zeebe, Operate, Tasklist, and Optimize.

It should be
1. Start Operate, Tasklist, and Optimize. (To create templates / alias in ES) (Will this work if Zeebe is not up and running?)
2. Stop Operate, Tasklist, and Optimize. 
3. Restore the state of [Operate](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/operate-tasklist-backup/), [Tasklist](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/operate-tasklist-backup/), and [Optimize](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/optimize-backup/).
4. Restore zeebe-records* indices from Elasticsearch snapshot.
5. Restore [Zeebe](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore/).
6. Start Zeebe, Operate, Tasklist, and Optimize.

Also I don't think that this is an edge case. In case of a disaster you of course need to create a brand new cluster based on the backups that you have.

**Comment by ManuelDittmar** [comment]
Hi @sdorokhova,
I created an example. It would be great if someone from engineering can validate this.
https://github.com/ManuelDittmar/backup-restore-demo

1. Start Zeebe, Operate, Tasklist, and Optimize. (To create templates / alias in ES) 
2. Stop Operate, Tasklist, and Optimize.
3. Delete all Indices
4. Restore the state of [Operate](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/operate-tasklist-backup/), [Tasklist](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/operate-tasklist-backup/), and [Optimize](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/optimize-backup/).
5. Restore zeebe-records* indices from Elasticsearch snapshot.
6. Restore [Zeebe](http://localhost:3000/docs/next/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore/).
7. Start Zeebe, Operate, Tasklist, and Optimize.

**Comment by sdorokhova** [comment]
Thank you @ManuelDittmar !
@johanwelgemoed the last comment from Manuel looks good to me! You can use it in case you have time to work on this issue. The only thing to may be add is that on the 1st step the applications must be properly configured, e.g. shards and replicas count. Ideally they reuse the same configuration as the initial application.
