### ISSUE TITLE
Webhooks docs say Camunda 7 only

### ISSUE THREAD

**Issue by matt-mckeithen** [camunda/camunda-docs#3754]
This page:

https://github.com/camunda/camunda-docs/blob/main/optimize_versioned_docs/version-3.13.0/self-managed/optimize-deployment/configuration/webhooks.md

and alert notifications here:

https://github.com/camunda/camunda-docs/blob/main/optimize_versioned_docs/version-3.13.0/self-managed/optimize-deployment/configuration/system-configuration.md 

Why?  These clearly work in Camunda 8.

**Comment by akeller** [comment]
Following up internally - https://camunda.slack.com/archives/C55U06YRG/p1714589889871179

**Comment by toco-cam** [comment]
Hello @matt-mckeithen,

Thanks for bringing this up. Technically, it might be possible to use Webhooks in Camunda 8 due to the legacy of Optimize, but it is not an officially supported feature. The biggest risk of using such features is that they are not tested explicitly for Camunda 8, and there is no migration path offered in case of changes with new versions of Optimize.

Regards Tobias (Product Management)

**Comment by matt-mckeithen** [comment]
Got it.  Is support for webhooks or some alternative on your roadmap?  Email only notifications is so 2000s 😁 .

**Comment by akeller** [comment]
@matt-mckeithen, you can follow the public issue here - https://github.com/camunda/issues/issues/735.

I will close this issue since we won't be able to make a change to the docs until the feature is officially supported.
