### ISSUE TITLE
Flow Control guide should explain that this is enabled per defautl in SaaS, but not in SM

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-docs#4283]
**Description**

Flow Control guide should explain that this is enabled per defautl in SaaS, but not in SM

**Issue observered**

I can (afaik) only find out that flow control is enabled in SaaS but disabled in SM by reading the release notes. https://docs.camunda.io/docs/next/reference/release-notes/860/#write-rate-limiting-based-on-exporting-rate-zeebe. 

**Suggestion for improvement**

Release Notes only summarize what was released. The core information (e.g., that a feature is enabled/disabled per default) should be part of the core docs.
Idea: add information about that this feature is enabled per default in SaaS to https://docs.camunda.io/docs/next/self-managed/operational-guides/configure-flow-control/

**Comment by lenaschoenburg** [comment]
>  Idea: add information about that this feature is enabled per default in SaaS to https://docs.camunda.io/docs/next/reference/release-notes/860/#write-rate-limiting-based-on-exporting-rate-zeebe.

You linked the release notes here again but I think you meant the operation guide? https://docs.camunda.io/docs/next/self-managed/operational-guides/configure-flow-control/

Unfortunately, this is in the self-managed section. If we want to explain our SaaS setup, I'd suggest we move this guide somewhere else. 

Do you also want us to document the specifics, i.e. the limits per cluster plan? I'd imagine this would quickly come up as a question otherwise.

**Comment by MaxTru** [comment]
>> Idea: add information about that this feature is enabled per default in SaaS to https://docs.camunda.io/docs/next/reference/release-notes/860/#write-rate-limiting-based-on-exporting-rate-zeebe.
>
> You linked the release notes here again but I think you meant the operation guide? https://docs.camunda.io/docs/next/self-managed/operational-guides/configure-flow-control/

Thanks @lenaschoenburg  - indeed. Corrected
