### ISSUE TITLE
Remove The Constant Interface Anti-Pattern

### ISSUE THREAD

**Issue by Shakior** [camunda/camunda-docs#4368]
https://docs.camunda.io/docs/components/best-practices/development/handling-data-in-processes/#using-constants-and-data-accessors
pls change it
public final class TwitterDemoProcessConstants {
  public static final String VAR_NAME_TWEET = "tweet";
  public static final String VAR_NAME_APPROVED = "approved";
}

**Comment by berndruecker** [comment]
Hey @Shakior - what is your problem with the class? 
Please also not it is not an interface - we simply use constants for the variable names instead of spreading their use throughout the code - which I think makes a ton of sense - especially as variable name are a shared contract between the process model and the Java code. So please provide more context to this issue or we need to close it. Thx!
