### ISSUE TITLE
Check links of documentation before pushing to production

### ISSUE THREAD

**Issue by menski** [camunda/camunda-docs#491]
With #453 we introduced a nightly link checker workflow and with #484 we introduced a PR based link check. Right now no external links are checked. For a PR based check we don't want to include the external link check, as it might block a PR merge based on external factors/availability.

To still be able to spot broken external links we could do the two following improvements:
- include external link checks to the nightly link check workflow
- include full link check (internal + external) in the release pipeline as a preliminary step before pushing to master

**Comment by akeller** [comment]
@pepopowitz would you say this is a duplicate? Or irrelevant now?

**Comment by pepopowitz** [comment]
I don't think it's a duplicate, but I do think it's irrelevant, or at least unimportant. Since I've started 20 months ago, I haven't heard of one problem with an external link. I don't think the validation is worth the effort.

It sounds like you're comfortable with it being closed too, so I'm going to close it.
